import { GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

import { useBitcoinDataSWR } from '@/infrastructure/hooks/useBitcoinDataSWR'
import { fetcher } from '@/libraries/fetcher'
import styles from '@/styles/Home.module.scss'

interface Props {
  fallbackData: BitflyerTickerResponseType
}

/**
 * @description ルートコンポーネント
 * 参考:
 * useSWR サンプル server-render
 * https://github.com/vercel/swr/blob/main/examples/server-render/pages/index.js
 */
const Home: React.FC<Props> = ({ fallbackData }) => {
  /**
   * @description useSWR のカスタムフック
   * getStaticProps からの fallbackDataを初期値に持つ。
   * クライアント側でのデータフェッチを行う。
   */
  const { data, mutate } = useBitcoinDataSWR(fallbackData)

  const onClickUpdateBtn = async (): Promise<void> => {
    const newData = await fetcher('/api/bitcoin')

    // データを更新（mutate）
    mutate(newData).catch((error) => {
      throw error
    })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className={styles.headerContenter}>
          <h1 className={styles.title}>最新のBitcoin情報</h1>
          <p className={styles.hp_tac}>bitflyer HTTP Public API から、最新のBitcoin情報を表示しています。</p>
        </div>
      </header>
      <main>
        <div className={styles.container}>
          {data ? (
            <div>
              <p>product_code: {data.product_code}</p>
              <p>timestamp: {data.timestamp}</p>
              <p>最低売り価格（best bid）: {data.best_bid}円</p>
              <p>最高売り価格（best ask）: {data.best_ask}円</p>
            </div>
          ) : (
            // <p>{data.product_code}</p>
            <p>loading……</p>
          )}
          <button onClick={onClickUpdateBtn}>Update to the Latest Info</button>
          <div className={styles.shopList}></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// eslint-disable-next-line import/no-default-export
export default Home

export const getStaticProps: GetStaticProps = async () => {
  const API_URL_ROOT = 'https://api.bitflyer.com/v1/getticker'

  const data = await fetcher(API_URL_ROOT)
  return {
    props: {
      fallbackData: data
    }
  }
}
